version: 0.2

phases:
  build:
    commands:
      - "sudo docker build -t opentrons-buildroot"
      - "sudo docker run --mount type=bind,source=$(pwd),destination=/buildroot opentrons-buildroot ot2_defconfig"
      - "sudo docker run --mount type=bind,source=$(pwd),destination=/buildroot opentrons-buildroot all"
artifacts:
  files:
    - output/images/sdcard.img
    - output/images/rootfs.tar.gz
    - output/images/rootfs.ext4
  name: linux-image
  discard-paths: yes
