version: 0.2

phases:
  pre_build:
    commands:
      - "docker build -t opentrons-buildroot ."
  build:
    commands:
      - ./opentrons-build.sh
artifacts:
  files:
    - output/images/ot2-system.zip
    - output/images/ot2-fullimage.zip
    - output/images/VERSION.json
  name: ot2-system
  discard-paths: yes
