version: 0.2

phases:
  pre_build:
    commands:
      - "docker build -t opentrons-buildroot ."
  build:
    commands:
      - ./opentrons-build.sh
artifacts:
  files:
    - output/images/rootfs.ext4
  name: ot2-system-$CODEBUILD_BUILD_ID
  discard-paths: yes
  secondary-artifacts:
    fullImage:
      files:
        - output/images/sdcard.img
      name: ot2-fullimage-$CODEBUILD_BUILD_ID
      discard-paths: yes
