version: 0.2

phases:
  pre_build:
    commands:
      - "docker build -t opentrons-buildroot ."
  build:
    commands:
      - ./opentrons-build.sh
artifacts:
  files:
    - output/images/sdcard.img
    - output/images/rootfs.tar.gz
    - output/images/rootfs.ext4
  discard-paths: yes
