#!/bin/sh

# Mount the /proc, /sys and /dev filesystems.
/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys
/bin/mount -t devtmpfs devtmpfs /dev

# use the /dev/console device node from devtmpfs if possible to not
# confuse glibc's ttyname_r().
# This may fail (E.G. booted with console=), and errors from exec will
# terminate the shell, so use a subshell for the test
if (exec 0</dev/console) 2>/dev/null; then
    exec 0</dev/console
    exec 1>/dev/console
    exec 2>/dev/console
fi

echo "--- GH0ST-IN-TH3-SH33LL---"

df
ls -lah /
ls /dev

#exec /sbin/init "$@"
setsid sh -c 'exec sh </dev/tty1 >/dev/tty1 2>&1'
#/bin/sh # ----------------> dropping into shell
