name: "Decide Opentrons Refs"
description: "Based on a subset of provided refs for an openembedded build, decide the rest."
inputs:
  token:
    description: "gh token for api calls to resolve refs"
    required: true
  monorepo:
    description: "ref of https://github.com/opentrons/opentrons to build"
    required: false
    default: "-"
  buildroot:
    description: "ref of https://github.com/opentrons/buildroot to build"
    required: false
    default: "-"
  monorepo-repo:
    description: "repo name for the monorepo (i.e. opentrons or opentrons-ot2)"
    required: false
    default: "opentrons"
outputs:
  monorepo:
    description: "the ref of the monorepo to use"
  buildroot:
    description: "the ref of the buildroot to use"
  build-type:
    description: "the type of build oe-core will create (develop, release)"
  variant:
    description: "Which variant to build (release, internal-release)"
  monorepo-repo:
    description: "Which repository under Opentrons to use for the monorepo (opentrons, opentrons-ot2)"
runs:
  using: 'node16'
  main: 'dist/index.js'
