#!/bin/sh

test $ID_MODEL_ID = "ed12" && test $ID_VENDOR_ID = "04d8" || exit 0

name="thermocycler_bootloader_volume"

# If the symlink does not yet exist, create it.
test -e "/dev/modules/$name" || ln -sf "$UM_MOUNTPOINT" "/dev/modules/$name"

exit 0